### ISSUE TITLE
Cache only if successful response

### ISSUE THREAD

**Issue by emibcn** [tanem/svg-injector#692] opened 2021-03-28 13:14 UTC
Hi there,
I'm using this library through [react-svg](https://github.com/tanem/react-svg) in a [server-less PWA I maintain](https://github.com/emibcn/covid). As a PWA, it caches the assets, so it can work offline. But some data-related assets are not downloaded until requested by the user. Sometimes, the user may forget to disable phone's _airplane mode_ before using the app. _Note:_ In this app, the SVG related component can be seen by adding a **Map Widget**.

I am developing an error boundary which allows re-rendering the errorish component once the source of the error have been fixed (for example, disabling phone's _airplane mode_). In this case, I expect the ReactSVG component to retry the download. Instead of that, it reuses a cached errorish version of the fetched data. _Note:_ Using DevTools Network, I am able to mock an initial error from server by blocking the SVG URL, and then "un-block" the net request for the SVG to retry the component render.

As a workaround, I create a global object where I store successful downloads by `src` (set on `afterInjection`) and set `react.svg`'s `useRequestCache` (same as this package's `cacheRequests`) to false until a successful download is detected.

I think it would be much better to don't cache errorish responses (unless -maybe- otherwise stated).

**Note:** I open the issue directly here, as I think the fix would be desired here, too, and the author is the same for both projects.

**Comment by jarretmoses** [comment] 2021-04-01 15:07
I believe I am running into this exact same issue too. Im personally going to downgrade react-svg for now.

**Comment by tanem** [comment] 2021-04-06 04:11
Sorry for the delay & thanks @emibcn, what you're suggesting sounds reasonable, I'll let you know when I have a PR ready.

**Comment by tanem** [comment] 2021-04-08 18:09
@emibcn just released #699 in [v10.0.0 of this library](https://github.com/tanem/svg-injector/tree/v10.0.0), and [v13.0.0 of react-svg](https://github.com/tanem/react-svg/tree/v13.0.0). Keen to hear if it helps your issue?

**Comment by emibcn** [comment] 2021-04-08 21:41
> Keen to hear if it helps your issue?

Yep! Thanks a lot!

Now executing build & deploy pipeline with last commit... ;)

**Comment by tanem** [comment] 2021-04-09 16:43
Closing as the issue is resolved now 🎉

**Closed as completed by tanem** 2021-04-09 16:43 UTC
